//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdealHires.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SortListedCandidate
    {
        public int Id { get; set; }
        public int JobId { get; set; }
        public int ProfileId { get; set; }
        public int CompanyId { get; set; }
        public bool IsSortListed { get; set; }
        public System.DateTime SortListedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Job Job { get; set; }
        public virtual Profile Profile { get; set; }
    }
}
