//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdealHires.DTO.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CandidateResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CandidateResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IdealHires.DTO.Resources.CandidateResource", typeof(CandidateResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccessToken.
        /// </summary>
        public static string AccessToken {
            get {
                return ResourceManager.GetString("AccessToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _AddEducation.
        /// </summary>
        public static string AddEducation {
            get {
                return ResourceManager.GetString("AddEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _AddWorkExp.
        /// </summary>
        public static string AddWorkExp {
            get {
                return ResourceManager.GetString("AddWorkExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already applied this job..
        /// </summary>
        public static string AlreadyAppliedJob {
            get {
                return ResourceManager.GetString("AlreadyAppliedJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already saved as &apos;Not Interested&apos;.
        /// </summary>
        public static string AlreadySavedNotInterested {
            get {
                return ResourceManager.GetString("AlreadySavedNotInterested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already saved this job..
        /// </summary>
        public static string AlreadySavedThisJob {
            get {
                return ResourceManager.GetString("AlreadySavedThisJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _AppliedJobList.
        /// </summary>
        public static string AppliedJobList {
            get {
                return ResourceManager.GetString("AppliedJobList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BasicEditSuccess.
        /// </summary>
        public static string BasicEditSuccess {
            get {
                return ResourceManager.GetString("BasicEditSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BasicEditSuccessNext.
        /// </summary>
        public static string BasicEditSuccessNext {
            get {
                return ResourceManager.GetString("BasicEditSuccessNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BasicFailure.
        /// </summary>
        public static string BasicFailure {
            get {
                return ResourceManager.GetString("BasicFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BasicSuccess.
        /// </summary>
        public static string BasicSuccess {
            get {
                return ResourceManager.GetString("BasicSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BtnBasicSuccess.
        /// </summary>
        public static string BtnBasicSuccess {
            get {
                return ResourceManager.GetString("BtnBasicSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BtnContactSuccess.
        /// </summary>
        public static string BtnContactSuccess {
            get {
                return ResourceManager.GetString("BtnContactSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BtnPreferencesSuccess.
        /// </summary>
        public static string BtnPreferencesSuccess {
            get {
                return ResourceManager.GetString("BtnPreferencesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidate Jobs get page ended.
        /// </summary>
        public static string CandidateJobsGetPageEnded {
            get {
                return ResourceManager.GetString("CandidateJobsGetPageEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidate Jobs post page ended..
        /// </summary>
        public static string CandidateJobsPostpgEnded {
            get {
                return ResourceManager.GetString("CandidateJobsPostpgEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContactEditSuccess.
        /// </summary>
        public static string ContactEditSuccess {
            get {
                return ResourceManager.GetString("ContactEditSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContactEditSuccessNext.
        /// </summary>
        public static string ContactEditSuccessNext {
            get {
                return ResourceManager.GetString("ContactEditSuccessNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContactFailure.
        /// </summary>
        public static string ContactFailure {
            get {
                return ResourceManager.GetString("ContactFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContactSuccess.
        /// </summary>
        public static string ContactSuccess {
            get {
                return ResourceManager.GetString("ContactSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeletedWork.
        /// </summary>
        public static string DeletedWork {
            get {
                return ResourceManager.GetString("DeletedWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteWorkFailure.
        /// </summary>
        public static string DeleteWorkFailure {
            get {
                return ResourceManager.GetString("DeleteWorkFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Education.
        /// </summary>
        public static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EducationDeleted.
        /// </summary>
        public static string EducationDeleted {
            get {
                return ResourceManager.GetString("EducationDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EducationDeleteFailure.
        /// </summary>
        public static string EducationDeleteFailure {
            get {
                return ResourceManager.GetString("EducationDeleteFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _EducationDetails.
        /// </summary>
        public static string EducationDetails {
            get {
                return ResourceManager.GetString("EducationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EducationEditSuccess.
        /// </summary>
        public static string EducationEditSuccess {
            get {
                return ResourceManager.GetString("EducationEditSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EducationFailure.
        /// </summary>
        public static string EducationFailure {
            get {
                return ResourceManager.GetString("EducationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EducationSuccess.
        /// </summary>
        public static string EducationSuccess {
            get {
                return ResourceManager.GetString("EducationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndAt.
        /// </summary>
        public static string EndAt {
            get {
                return ResourceManager.GetString("EndAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error details job interested get.
        /// </summary>
        public static string ErrorDetailsJobInterestedGet {
            get {
                return ResourceManager.GetString("ErrorDetailsJobInterestedGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error details preference get .
        /// </summary>
        public static string ErrorDetailsPreferenceGet {
            get {
                return ResourceManager.GetString("ErrorDetailsPreferenceGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidate JobApplied get page started.
        /// </summary>
        public static string JobAppliedGetPageStarted {
            get {
                return ResourceManager.GetString("JobAppliedGetPageStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job applied successfully..
        /// </summary>
        public static string JobAppliedMsg {
            get {
                return ResourceManager.GetString("JobAppliedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _JobApplied.
        /// </summary>
        public static string JobAppliedPartial {
            get {
                return ResourceManager.GetString("JobAppliedPartial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JobExploreFailure.
        /// </summary>
        public static string JobExploreFailure {
            get {
                return ResourceManager.GetString("JobExploreFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _JobInterested.
        /// </summary>
        public static string JobInterested {
            get {
                return ResourceManager.GetString("JobInterested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _JobRecommended.
        /// </summary>
        public static string JobRecommended {
            get {
                return ResourceManager.GetString("JobRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job saved successfully..
        /// </summary>
        public static string JobSavedMsg {
            get {
                return ResourceManager.GetString("JobSavedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JobsFailure.
        /// </summary>
        public static string JobsFailure {
            get {
                return ResourceManager.GetString("JobsFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _JobsPartial.
        /// </summary>
        public static string JobsPartial {
            get {
                return ResourceManager.GetString("JobsPartial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotificatioAddSucess.
        /// </summary>
        public static string NotificatioAddSucess {
            get {
                return ResourceManager.GetString("NotificatioAddSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotifiactionDetails.
        /// </summary>
        public static string NotificationDetails {
            get {
                return ResourceManager.GetString("NotificationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotificationFailure.
        /// </summary>
        public static string NotificationFailure {
            get {
                return ResourceManager.GetString("NotificationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _NotInterestedJobList.
        /// </summary>
        public static string NotInterestedJobList {
            get {
                return ResourceManager.GetString("NotInterestedJobList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Not Interested&apos; saved successfully..
        /// </summary>
        public static string NotInterestedSavedMsg {
            get {
                return ResourceManager.GetString("NotInterestedSavedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Preferences.
        /// </summary>
        public static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PreferencesEditSuccess.
        /// </summary>
        public static string PreferencesEditSuccess {
            get {
                return ResourceManager.GetString("PreferencesEditSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PreferencesEditSuccessNext.
        /// </summary>
        public static string PreferencesEditSuccessNext {
            get {
                return ResourceManager.GetString("PreferencesEditSuccessNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PreferencesFailure.
        /// </summary>
        public static string PreferencesFailure {
            get {
                return ResourceManager.GetString("PreferencesFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PreferencesPreviewEditSuccess.
        /// </summary>
        public static string PreferencesPreviewEditSuccess {
            get {
                return ResourceManager.GetString("PreferencesPreviewEditSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PreferencesSuccess.
        /// </summary>
        public static string PreferencesSuccess {
            get {
                return ResourceManager.GetString("PreferencesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Preview.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _PreviewAddPreferences.
        /// </summary>
        public static string PreviewAddPreferences {
            get {
                return ResourceManager.GetString("PreviewAddPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _PreviewEducationDetails.
        /// </summary>
        public static string PreviewEducationDetails {
            get {
                return ResourceManager.GetString("PreviewEducationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _PreviewPreference.
        /// </summary>
        public static string PreviewPreference {
            get {
                return ResourceManager.GetString("PreviewPreference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _PreviewWorkDetails.
        /// </summary>
        public static string PreviewWorkDetails {
            get {
                return ResourceManager.GetString("PreviewWorkDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record not found..
        /// </summary>
        public static string RecordNotFound {
            get {
                return ResourceManager.GetString("RecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to response.
        /// </summary>
        public static string Response {
            get {
                return ResourceManager.GetString("Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _SavedJobList.
        /// </summary>
        public static string SavedJobList {
            get {
                return ResourceManager.GetString("SavedJobList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selectJobTypes completed.
        /// </summary>
        public static string SelectJobTypesCompleted {
            get {
                return ResourceManager.GetString("SelectJobTypesCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _ShortNotificationDetails.
        /// </summary>
        public static string ShortNotification {
            get {
                return ResourceManager.GetString("ShortNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to we don’t have appropriate job posted for company your are looking for, Here are similar type of jobs with other companies.
        /// </summary>
        public static string SimilarJobMsg {
            get {
                return ResourceManager.GetString("SimilarJobMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some error occurred..
        /// </summary>
        public static string SomeError {
            get {
                return ResourceManager.GetString("SomeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidate JobExplore post page ended..
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tokenData.
        /// </summary>
        public static string TokenData {
            get {
                return ResourceManager.GetString("TokenData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _WorkDetails.
        /// </summary>
        public static string WorkDetails {
            get {
                return ResourceManager.GetString("WorkDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _WorkExp.
        /// </summary>
        public static string WorkExp {
            get {
                return ResourceManager.GetString("WorkExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkExpEditSuccess.
        /// </summary>
        public static string WorkExpEditSuccess {
            get {
                return ResourceManager.GetString("WorkExpEditSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkExpFailure.
        /// </summary>
        public static string WorkExpFailure {
            get {
                return ResourceManager.GetString("WorkExpFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkExpSuccess.
        /// </summary>
        public static string WorkExpSuccess {
            get {
                return ResourceManager.GetString("WorkExpSuccess", resourceCulture);
            }
        }
    }
}
