//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdealHires.DTO.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmployerResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmployerResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IdealHires.DTO.Resources.EmployerResource", typeof(EmployerResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _BuyJobCredits.
        /// </summary>
        public static string BuyJobCredits {
            get {
                return ResourceManager.GetString("BuyJobCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CandidateList.
        /// </summary>
        public static string CandidateList {
            get {
                return ResourceManager.GetString("CandidateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeletedWork.
        /// </summary>
        public static string DeletedWork {
            get {
                return ResourceManager.GetString("DeletedWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteWorkFailure.
        /// </summary>
        public static string DeleteWorkFailure {
            get {
                return ResourceManager.GetString("DeleteWorkFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployerDashboard.
        /// </summary>
        public static string EmployerDashboard {
            get {
                return ResourceManager.GetString("EmployerDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployerJobs post page ended..
        /// </summary>
        public static string EmployerJobsPostpgEnded {
            get {
                return ResourceManager.GetString("EmployerJobsPostpgEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IHDashboard.
        /// </summary>
        public static string InternalDashboard {
            get {
                return ResourceManager.GetString("InternalDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JobDetails.
        /// </summary>
        public static string JobDetails {
            get {
                return ResourceManager.GetString("JobDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JobExploreFailure..
        /// </summary>
        public static string JobExploreFailure {
            get {
                return ResourceManager.GetString("JobExploreFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not sufficient job credit to post the job. please buy job credits..
        /// </summary>
        public static string LessJobCredit {
            get {
                return ResourceManager.GetString("LessJobCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _PostedNewJob.
        /// </summary>
        public static string PostedNewJob {
            get {
                return ResourceManager.GetString("PostedNewJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostJob.
        /// </summary>
        public static string PostJob {
            get {
                return ResourceManager.GetString("PostJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Preferences.
        /// </summary>
        public static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Preview.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _PreviewJobBasic.
        /// </summary>
        public static string PreviewJobBasic {
            get {
                return ResourceManager.GetString("PreviewJobBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to response.
        /// </summary>
        public static string Response {
            get {
                return ResourceManager.GetString("Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved successfully..
        /// </summary>
        public static string SavedSuccessfully {
            get {
                return ResourceManager.GetString("SavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some error occured..
        /// </summary>
        public static string SomeErrorOccured {
            get {
                return ResourceManager.GetString("SomeErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sufficient job credit is available.Your current job credit is .
        /// </summary>
        public static string SufficientJobCredit {
            get {
                return ResourceManager.GetString("SufficientJobCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tokenData.
        /// </summary>
        public static string TokenData {
            get {
                return ResourceManager.GetString("TokenData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been credited successfully..
        /// </summary>
        public static string TransactionSuccessful {
            get {
                return ResourceManager.GetString("TransactionSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _WorkExp.
        /// </summary>
        public static string WorkExp {
            get {
                return ResourceManager.GetString("WorkExp", resourceCulture);
            }
        }
    }
}
